#!/bin/sh
alias poff='sudo systemctl poweroff'
alias reboot='sudo systemctl reboot'

alias ll='ls -ls'
alias la='ls -lsa'
alias ld='du -h -d 1 | sort -hr'
alias ls='ls --color=auto'

alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."
alias .........="cd ../../../../../../../.."
alias ..........="cd ../../../../../../../../.."
alias ...........="cd ../../../../../../../../../.."
alias ............="cd ../../../../../../../../../../.."

command -v pacman >/dev/null
if [ $? -eq 0 ]; then
    alias agu='sudo pacman -Suy'
    alias agi='sudo pacman -S'
    alias agr='sudo pacman -R'
fi

command -v apt >/dev/null
if [ $? -eq 0 ]; then
    alias agu='sudo apt-get update && sudo apt-get upgrade'
    alias agi='sudo apt-get install'
    alias agr='sudo apt-get remove'
fi

alias zp='tar -zcvf'
alias uzp='tar -zxvf'

alias pdf='zathura'
alias vim='nvim'

alias ga='git add'
alias gap='git add . --patch'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias ggui='git gui'
alias gf='git fetch --all -p'
alias gl='git log'
alias gm='git merge'
alias gpl='git pull'
alias gpu='git push'
alias grb='git rebase'
alias grs='git reset'
alias gs='git status'
alias gr='git remote -v'
alias gsui='git submodule update --init'
alias gico='git-interactive-checkout'
alias gid='git-select-revision git diff'
alias gidl='git-dl-review'
alias gim='git-select-revision git merge'
alias girb='git-select-revision git rebase'
alias gis='git-select-revision echo'
alias gfm='git-find-merged'
alias gfdm='git-find-merged usr/${USER} | xargs -L1 git branch -D'
alias gfu='git-find-unmerged'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'

alias grp='groups | sed -e "s/ /\n/g" | fzf --height 20'

alias rlc='repo forall -p -c git show -s --format="%H - %cI - %cn: %s"'
alias rsd='repo sync -d -j8'
alias rst='repo status'
alias rfm='repo forall -p -c "git find-merged"'
alias rfdm='repo forall -p -c "git find-merged usr/${USER} | xargs -L1 git branch -D"'
alias rfu='repo forall -p -c "git find-unmerged"'
alias rsy='repo sync -j8'

alias sclrst='sudo systemctl restart'
alias sclstart='sudo systemctl start'
alias sclstatus='sudo systemctl status'
alias sclstop='sudo systemctl stop'

alias bh='bin_helper'

alias ss='gnome-screenshot -i'
alias yaml2js='python -c '\''import sys, yaml, json; json.dump(yaml.load(sys.stdin, Loader=yaml.SafeLoader), sys.stdout, indent=4)'\'''
