#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Local X11 config
if [ -f ~/.local/.xinitrc_local ]; then
    . ~/.local/.xinitrc_local
fi

setxkbmap de
setxkbmap -option caps:escape &

xset dpms 300 0 1800
xset +dpms

picom -b --config ~/.config/picom/picom.conf

# Background picture to use
if [ -f ~/.local/desktop_bg ]; then
    DESKTOP_BG=$(cat ~/.local/desktop_bg)
    feh --no-fehbg --bg-scale "${DESKTOP_BG}"
fi

i3

