#!/bin/bash
# Use fzf to select a git revision and check it out
REVISIONS="$(git branch -a | sed -e 's/^[ \*]*//')\n$(git tag -l)\n$(git rev-list --all)"
if [ -z $1 ]; then
    SELECTED_REVISION=$(echo "${REVISIONS}" | fzf --height 20)
else
    SELECTED_REVISION=$(echo "${REVISIONS}" | grep $1 | fzf --height 20)
fi

if [[ $? -eq 0 ]]; then
    git checkout ${SELECTED_REVISION}
fi
